### PR TITLE
Feature sprint5 s 01060 locations

### PR DESCRIPTION
**Pull request by verbeen**
- Map on create job page
  - Autocomplete textual address search
  - Clicking on map gives suggestion for an address
  - Mix and match between written address, suggested addresses & coordinates
- Map on job detail page
  - Simple view of location of the job
- Map on job list page
  - Autocomplete textual address search. Entering an address here puts the marker on the accompanying address 
  - Radius selection, updates immediately.
  - Search utilizes geographical coordinate search
  - Minor tweak to geo search on mongodb - using geoWithin instead of nearSphere
  - Markers close by eachother are clustered

### CODE REVIEW

**Comment by ghost** [comment]
Works as expected.

Tested:
-Creation of job offers with a selected address and map coordinates
-Searching of job offers by address and location

Suggestions:
-Location and map should be marked with an asterix (*) to let the user know that the field is mandatory before saving a new job offer
-Map doesn't update to location when address is entered for the first time
-Rename of location field to address

**Comment by ghost** [comment]
Skill search in combination with location also tested successfully.

**Comment by verbeen** [comment]
Fixed:
- Location and map should be marked with an asterix (*) to let the user know that the field is mandatory before saving a new job offer
- Map doesn't update to location when address is entered for the first time
- Rename of location field to address

**Comment by achala93** [comment]
Thumbs up!!!
Works as expected.
Suggestion: The settings for selection are lost when we view job details.

**Pull request merged**
