### PR TITLE
Feature sprint4 stats and multi offers

### PR DESCRIPTION
**Pull request by verbeen**
US S-01016
- Created page where a company can select multiple CSV files, parse them and then upload them.
- Created REST API call that can be used to upload job offers in bulk
- Created JobOfferStore function to insert job offers in bulk, so that if it fails, it fails as a whole.
- CSVs have to have a header which corresponds to the data transfer model (the right header names)
- This can be used locally instead of the DataGenerator now

US S-01018
- Created page where company can see all the statistics on all their job offers
- Created REST API call that returns all the job offer statistics
- Created Event system to decouple the statistics from the actual REST API. Storing metrics shouldn't be called directly since it's meta-information. The asynchronous event system handles this
- Created datamodel and subsequent Store to manage, store and load the statistical (metric) data.
- This could be extended to contain data on the specific users, for further statistical analysis.

### CODE REVIEW

**Comment by vishnusr831** [comment]
thumbs up
Working as expected except the apply statistics
OK for dev server

**Comment by verbeen** [comment]
Good.
Apply statistics are not included at the moment - reason is that there would have to be a dedicated API call for the statistics of that one button and that goes counter to the usage here. My proposal is to leave that statistic for what it is at the moment, and when we're actually using the Apply button server side, we can fire off an event. 

The events are very extensible so we can be flexible in this regard.

**Comment by ghost** [comment]
Tested basic functionality: create students, company, job offers and searching.
Functions work as expected
Statistics work.
-Extensions: Display job offer title, exclude company clicks and views from statistics
Mulitple job offers:
-Extensions: improve recognition of valid csv files (e.g. by number of rows and colums), currently other files get accepted as well but have errors when uploading after parsing

-> Go for V2.

**Comment by achala93** [comment]
Thumbs up!!
I could notice three errors..
1. Presence of apply field in job profile when user is logged in as company.
2. Apply statistics does not work.
3. Job metric page loading problem.
Rest works fine.

**Comment by verbeen** [comment]
- Couldn't reproduce the non-display of the metrics on first page load - perhaps it was because of a faulty page refresh the first time it was used. Add as issue should this happen again
- Presence of apply field we can add to next sprint

Just merged with develop, everything still working - ready to merge to develop.

**Pull request merged**
