### PR TITLE
Feature sprint 5  delete job as company

### PR DESCRIPTION
**Pull request by vishnusr831**
Implemented Deletion of jobs by company-

Story points-
Deletion of jobs by company
Only the same company should be able to delete their jobs

Tested and working properly.

### CODE REVIEW

**Comment by toaditoad** [comment]
You have to pull the code from the develop branch into your feature branch first and resolve the conflicts.

**Comment by toaditoad** [comment]
Looks good to me. I just implemented the date filter to check for n/a date.

**Comment by ghost** [comment]
Tested and works. N/A date gets also displayed.

**Comment by verbeen** [comment]
This feature is not done. The metrics are not removed.

Will add as defect to versionone, so we can fix it tomorrow.

**Pull request merged**
