### PR TITLE
Sprint 3 features

### PR DESCRIPTION
**Pull request by verbeen**
The actual merge to master which should be functionally complete for the third sprint. See merge request to develop for full details.

### CODE REVIEW

**Comment by verbeen** [comment]
tested:
register & login student, admin, company
admin view all job offers, users
search job offers student, not logged in
company create job offer
student apply job offer

no errors found

**Comment by ghost** [comment]
tested creating student, admin and company account
tested job offer search with various records
tested job offer creation
tested admin job offer and user views

3 Minor issues found and documented in Version1

Verdict for pull request:
-> GO!

**Comment by toaditoad** [comment]
### Story S-01023

Arnold, the administrator of the JfS portal would like to have an overview page on the website where he can see all the current job offers posted. To have a better overview on the information he wants to be able to filter the data based on the dates or company names. This is convenient for Arnold as he has to frequently look up on job offer and to respond to queries from the companies.  

### Acceptance Criteria:

An administrator can log-in to the JfS portal with his credentials and navigate to a page to see the job listings and filter them based on dates and/or company name. **(succeeded)**

**Comment by vishnusr831** [comment]
Story S-01024
As an administrator I would like to have an overview of all the users so that I don’t have to query the database
DESCRIPTION:
Arnold, the administrator of the JfS portal would like to have an overview page on the website where he can see all the registered users. He wants this information for statistical purpose and for planning for any scalability and performance issues.
 Acceptance criteria:
Admin is about to see all the users in the system
--[succeeded]

**Comment by ghost** [comment]
commissioned by Achala:
Story S-01020 As a student I want to register an account so that I can apply for job offers
Story S-01039 As a student I want to be able to login with my personal account so that I can apply to job offers

tested successfully.
--[succeeded]

**Comment by DeepikaPrasad** [comment]
Story S-01014:As a company I want to be able to enter a job offer so that I can get potential candidates for the job opening

Acceptance Criteria:
A new job is created and appears in the search results.

Tested, successful.

**Pull request merged**
