### PR TITLE
Feature subscription sprint4

### PR DESCRIPTION
**Pull request by ghost**
User-Story Notification Pull request:

### CODE REVIEW

**Comment by ghost** [comment]
-tested: 
adding, updating, subscription for user
testing querys with types, skills and location
verifying last view date is considered, user layout

-verified:
job offer, registration etc. is still working

**Comment by vishnusr831** [comment]
Tested-
Existing functionality working as expected
Subscription functionality also working as expected

**Comment by verbeen** [comment]
Bugs found:
- If type is unselected an exception is thrown in the backend. This is because conversion from DTO to DO doesn't do a null check before calling the function name() on the field types.
- In subscriptionDTO/DO the types field holds only one value. Should be called type instead
- When you click on the 'Manage notifications' button a ? mark is added to the address in the address bar. Indicating that some kind of query paramater is added, which should not be the case.

Result: 
Implement these fixes before merging

**Comment by verbeen** [comment]
More points:

JFSGui:
- add-notification.html/js& style.css in student/notification folder in JFSGui do not follow the naming convention. Should be student-notification.html/js/css.
- Manage notifications button is of input type in a form, even though it's just a href. Change to a normal button since there is no input.
- In the directive the page is called Notifications, but it's the landing page (student-landing.html). The proper name should be reflected so this should be Landing, or home or somesuch.

JFSService:
- Use serializer instead of new Gson() in studentsubscriptionstore.

**Comment by verbeen** [comment]
More:

JFSService:
JobOfferStore.getOffersByCriteria
-    delayForDisplay - naming perhaps unclear? perhaps resultsFrom? and why is it a separate criteria instead of being included in the StudentSubscriptionsDO?
- the first IF check, checks for location != null and empty string check, even though it's for "type", that should be removed. It also doesn't do a null check for types (you wouldn't need the all type if you did that).
- The skills are sent as a string containing Comma Separated Values (CSV). You should sent this as a normal array with strings instead. Parse the CSV before you send it to the server.

**Comment by ghost** [comment]
- If type is unselected an exception is thrown in the backend. This is because conversion from DTO to DO doesn't do a null check before calling the function name() on the field types.
- -> fixed
- the first IF check, checks for location != null and empty string check, even though it's for "type", that should be removed. It also doesn't do a null check for types (you wouldn't need the all type if you did that).
- -> fixed

**Comment by ghost** [comment]
- In subscriptionDTO/DO the types field holds only one value. Should be called type instead
- -> Lots of work and testing in both fe and be, corrupt mongo db -> would reject it for now or do it on the weekend
- When you click on the 'Manage notifications' button a ? mark is added to the address in the address bar. Indicating that some kind of query paramater is added, which should not be the case
- -> need more information, can't reproduce it

**Comment by verbeen** [comment]
- on the backend its just a refactor, (shift+f6 in intellij idea) frontend you need to do a search including strings i guess. but it's only used on one or two pages isn't it? just a refactor i'd say and will prevent any future confusion.
- /?#/student.... the question mark is there at the start

**Comment by ghost** [comment]
- Use serializer instead of new Gson() in studentsubscriptionstore.
- -> fixed
- delayForDisplay - naming perhaps unclear? perhaps resultsFrom? and why is it a separate criteria instead of being included in the StudentSubscriptionsDO?
- -> name is fixed, good point about implementing it in StudentSubscriptionsDO could be done on the weekend, we will discuss it though then every student could set it by himself?
- The skills are sent as a string containing Comma Separated Values (CSV). You should sent this as a normal array with strings instead. Parse the CSV before you send it to the server.
- -> good point, we will discuss it

**Pull request merged**
