### PR TITLE
Feature sprint 5  delete job as company

### PR DESCRIPTION
**Pull request by vishnusr831**
Implemented Deletion of jobs by company-

Story points-
Deletion of jobs by company
Only the same company should be able to delete their jobs

Tested and working properly.

### CODE REVIEW

**Comment by DeepikaPrasad** [comment]
Hi Vishnu,

I tested your code. It is functional and works as excepted. Good job! 

However, I see that the job offer dates (start date and valid until) defaults to 1970-01-01 if it is null. You can use the date filter that Thorsten has implemented. Also you can show a confirmation message after a job offer is deleted.

**Comment by vishnusr831** [comment]
Thank you Deepika,

About the confirmation message, if the company want to delete bulk orders, then it will not be a good idea.

So if there are no problem, i will proceed with merging.

**Comment by DeepikaPrasad** [comment]
Hi Vishnu,
I guess you mean deleting job offers (not orders) :-) in bulk. When i tested i did not see an option to delete job offers in bulk. Is this implemented? My comment on the confirmation message was: display a message _after_ the job offer was deleted so that we are consistent. Anyways, it's just my opinion.
See screenshot below:

admin_delete_joboffer

**Comment by vishnusr831** [comment]
Got your point Deepika,

Implemented confirmation message box also.

**Comment by toaditoad** [comment]
PLEASE DO NOT MERGE THIS PULL REQUEST!

The branch should be merged to the develop branch, not to master directly!
Besides that, please, first pull the most recent code from the develop branch into your feature branch. So, you can check if your implementation works fine with other (new) features.

**Comment by toaditoad** [comment]
Closing this pull request now.

**Pull request closed without merging**
