### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by verbeen**
Contains (for more information see pull requests):
- US S-01016
  As a company I want to be able to upload multiple job offers so that company can manage bulk job offerings effectively 
- US S-01018
  As a company I want to have statistics on visitors and clicks on the offer so that I have data for analysis 
- US S-01022
  As a student I want to subscribe for notifications about job offers that fit certain criteria 
- US S-01036
  Unit-Tests: As a product owner I want to have Unit/Integration-Tests 
- Defect D-01002
  ISSUE: Page refresh results in a "Not found" 
- Defect D-01003
  ISSUE: Registration always returns successful (error handling is not correct)

### CODE REVIEW

**Comment by verbeen** [comment]
Tested Multi job offer addition & Statistics, both pass.

**Comment by toaditoad** [comment]
Tested subscription/notification feature -> Passed

Enhancements hints for next sprint:
- naming of "notifications" to singular expression to make sure a user can just have one subscription at a time
- minor UI changes to adapt views to the rest of the page to make a little bit cleaner

**Comment by vishnusr831** [comment]
As discussed , the upload option is not working as expected once you upload a wrong file.
Need to be resolved before moving

**Comment by verbeen** [comment]
Would be nice if logout and login is on rightside of navbar

**Comment by achala93** [comment]
Thumbs up!!
The two defects are solved. Other features are working fine.
Minor issues found:
1. Presence of apply button when user is logged in as company.
2. Apply statistics does not work.

**Comment by ghost** [comment]
Tested subscrition and existing features regarding registration, job offer creation.
All pass.

**Comment by verbeen** [comment]
Fixed 
- As discussed , the upload option is not working as expected once you upload a wrong file.
  Need to be resolved before moving

**Comment by verbeen** [comment]
Fixed
- Issue where setting jobOfferChooser.value to empty on page load would cause readonly error. Now only  setting value to empty when clicking upload more.

**Comment by verbeen** [comment]
Alright, thumbs up for me, so say we all??

**Comment by toaditoad** [comment]
Go Go Go!

**Comment by vishnusr831** [comment]
Thumbs up up !!

**Pull request merged**
