### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by verbeen**
- S-01025 As an administrator I want to delete student and company accounts 
- S-01034 As a company I want to see and delete job offers 
- S-01041 As an administrator I want to delete jobs on the admin page 
- S-01044 As a company I want to be able to select Other as a job type for any jobs that don't fit the given categories
- S-01052 As a user I want to search for job offers by specific skills (including partial matches)  
- S-01058 As a user I want to have a consistent, clean and spell-checked user interface 
- S-01059 As a product owner I want well-documented and clean source code 
- S-01060 As a user I want to see which locations I'm entering when adding them

### CODE REVIEW

**Comment by verbeen** [comment]
Small suggestions: 
- Go back to login page when you log out. No need for special page informing you're logged out - it's to be assumed.
- Landing pages should be useful, not what we have now: Student go to Notification page, Company go to Job Create page, Admin go to job offers page
- Name of admin navigation pages shouldn't include admin in the word: Manage job offers instead of Admin job offers and Manage users instead of Admin users

**Comment by verbeen** [comment]
Tested:
- S-01025 As an administrator I want to delete student and company accounts
  Everything was removed after I deleted the accounts and Patrick and Vishnu had to recreate their accounts and job offers. So works as intended!

**Comment by verbeen** [comment]
Suggestion:
On the navigation, with a company account, Delete jobs should perhaps be Job management

**Comment by verbeen** [comment]
Tested:
- S-01034 As a company I want to see and delete job offers

Job offers and their metrics get deleted as expected. Works.

**Comment by verbeen** [comment]
Checked:
- S-01059 As a product owner I want well-documented and clean source code
  Plenty of comments.

**Comment by vishnusr831** [comment]
S-01041 As an administrator I want to delete jobs on the admin page
-in the navigation page, the heading should be something like manage jobs, rather than admin job offers.Same case for the Admin users.

S-01044 As a company I want to be able to select Other as a job type for any jobs that don't fit the given categories
-TESTED OK

**Comment by ghost** [comment]
Successfully Tested user stories:
S-01052 As a user I want to search for job offers by specific skills (including partial matches)
-> also retested notifcation tests
S-01058 As a user I want to have a consistent, clean and spell-checked user interface
-> check for consistency in terminology and spelling

Suggestion:
Put space between asterix/\* and address and map on job offer creation.

**Comment by vishnusr831** [comment]
S-01025 As an administrator I want to delete student and company accounts

In the Admin -Delete user page , if we try to delete the user then-"The user has been deleted successfully." is displayed where it should not be any delete button for admin or a message should be displayed as "Admin cant be deleted" or something

**Comment by ghost** [comment]
Suggestion: React to "Enter" button also in seach fields of job offer main page (Currently this works in admin pages already.)

**Comment by vishnusr831** [comment]
Main job offer display page.Small glitches are there as in the attachment.
jobdetail age
jobofferpage

**Comment by verbeen** [comment]
- Administrate users heading changed to Manage users
- Fixed wrong error handling on delete user page
- Changed job offer management page look to have some whitespace on both sides.

**Comment by vishnusr831** [comment]
If you click on the logo in the webpage, its leading to the old landing page(with token and all)

**Pull request merged**
